name: Setup python, scons and golang
description: Setup python, install the pip version of scons and setup golang.
inputs:
  python-version:
    description: The Python version to use.
    default: 3.x
  python-arch:
    description: The Python architecture.
    default: "x64"
  go-version:
    description: The Go version to use.
    default: "1.22.3"
  scons-version:
    description: The SCons version to use.
    default: 4.8.0

runs:
  using: composite
  steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        # Semantic version range syntax or exact version of a Python version.
        python-version: ${{ inputs.python-version }}
        # Optional - x64 or x86 architecture, defaults to x64.
        architecture: ${{ inputs.python-arch }}

    - name: Setup SCons
      shell: bash
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install wheel
        python -m pip install scons==${{ inputs.scons-version }}
        scons --version

    # Setup Golang
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Check Go version
      shell: bash
      run: go version
