name: 'zip-upload-split'

description: 'Split zip and upload 2G release parts'

inputs:
  zip-path:
    description: 'Zip file to split'
    required: true
  release-id:
    description: 'Release identifier'
    required: true
  token:
    description: 'Github Token'
    required: true
  zip-cmd:
    description: 'Select zipping software ( "7zip", "zip" )'
    required: false
    default: '7zip'

runs:
  using: "composite"
  steps:
    - name: Upload Release Asset
      shell: bash
      env:
        # Github upload limit is less than stated 2147483648 bytes (2147483k).
        MAX_SIZE: 2050000
      run: |
          mkdir _temp
          NAME=$( basename ${{ inputs.zip-path }} )
          if [ ${{ inputs.zip-cmd }} == '7zip' ]; then
            sudo apt install -y 7zip;
            7z a -tzip -v${MAX_SIZE}k _temp/${NAME} ${{ inputs.zip-path }};
          else
            zip ${{ inputs.zip-path }} --out _temp/${NAME} -s "${MAX_SIZE}k";
          fi
          tree
          cd _temp
          for file in *; do \
            echo -e "Uploading $file...\n"; \
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ inputs.token }}" \
              -H "Content-Type: application/zip" \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ inputs.release-id }}/assets?name=${file}" \
              -T "${file}"; \
            done
            cd .. && rm -r _temp
