name: 'zip-upload-split'

description: 'Split zip and upload 2G release parts'

inputs:
  zip-path:
    description: 'Zip file to split'
    required: true
  release-id:
    description: 'Release identifier'
    required: true
  token:
    description: 'Github Token'
    required: true
  zip-cmd:
    description: 'Select zipping software ( "7zip", "zip" )'
    required: false
    default: '7zip'

runs:
  using: "composite"
  steps:
    - name: Upload Release Asset
      shell: bash
      env:
        # Github upload limit is less than stated 2147483648 bytes (2147483k).
        MAX_SIZE: 2050000000
        MAX_SIZE_K: 2050000
      run: |
          mkdir _temp
          NAME=$( basename ${{ inputs.zip-path }} )
          SIZE=$( stat -c %s ${{ inputs.zip-path }} )
          if [ "${SIZE}" -le MAX_SIZE ]; then
            cp ${{ inputs.zip-path }} _temp/${NAME};
          elif [ ${{ inputs.zip-cmd }} == '7zip' ]; then
            # On ubuntu-22.04 and ubuntu-24.04 apt package has a bug
            # https://sourceforge.net/p/sevenzip/bugs/2407/
            # sudo apt install -y 7zip;
            curl -O "https://www.7-zip.org/a/7z2409-linux-x86.tar.xz";
            tar -xvf 7z2409-linux-x86.tar.xz "7zz";
            chmod +x 7zz;
            ./7zz a -tzip -v${MAX_SIZE_K}k _temp/${NAME} ${{ inputs.zip-path }};
            rm 7z2409-linux-x86.tar.xz 7zz
          else
            # unknown zip bug can corrupt files in split archives 
            zip ${{ inputs.zip-path }} --out _temp/${NAME} -s "${MAX_SIZE_K}k";
          fi
          tree
          cd _temp
          for file in *; do \
            echo -e "Uploading $file...\n"; \
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ inputs.token }}" \
              -H "Content-Type: application/zip" \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ inputs.release-id }}/assets?name=${file}" \
              -T "${file}"; \
            done
            cd .. && rm -r _temp
