name: Squash
on:
  push:
    branches: [xr2]
permissions:
  contents: write
jobs:
  dispatch:
    name: Dispatch
    env:
     # GITHUB_TOKEN: ${{ secrets.SQUASH1 }}
      INPUT_REPO_TOKEN: GITHUB_TOKEN
      INPUT_BRANCH: main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['dragonhunt02/godot']
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: cron-patch
          fetch-depth: 0
      - name: Dispatch to workflow 
        run: |
            sudo apt install -y tree
            git status

            git log -n 5
            git reset --soft HEAD~2
            # rm -f .github/workflows/dispatch.yaml
            git config --global user.email "jackhunt43@libero.it"
            git config --global user.name "dragonhunt02"
            git add -A
            git commit -a -m 'Add automated nightly pruning'
            git log -n 5
            git status
            git push -f
            exit 1
